#!/usr/bin/env python3
from __future__ import annotations

import argparse
import configparser
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def lua_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", default=str(ROOT / "out" / "mods" / "return-to-tristram"))
    args = parser.parse_args()
    output_root = Path(args.output)
    generated = output_root / "lua" / "mods" / "rtt" / "generated"
    generated.mkdir(parents=True, exist_ok=True)

    ids_path = ROOT / "config" / "content-ids.json"
    save_path = ROOT / "config" / "save-schema.json"
    network_path = ROOT / "config" / "network-policy.json"
    features_path = ROOT / "config" / "features.ini"
    table_map_path = ROOT / "config" / "table-map.json"

    ids = json.loads(ids_path.read_text(encoding="utf-8"))
    save = json.loads(save_path.read_text(encoding="utf-8"))
    network = json.loads(network_path.read_text(encoding="utf-8"))
    table_map = json.loads(table_map_path.read_text(encoding="utf-8"))
    features = configparser.ConfigParser()
    features.optionxform = str
    features.read(features_path, encoding="utf-8")

    entry_lines = []
    for entry in ids["entries"]:
        entry_lines.append(
            "    [%s] = { namespace = %s, symbol = %s, status = %s },"
            % (lua_string(entry["id"]), lua_string(entry["namespace"]), lua_string(entry["symbol"]), lua_string(entry["status"]))
        )
    ids_lua = "\n".join([
        "-- GENERATED by scripts/generate-framework-data.py; do not edit.",
        "return {",
        f"  schemaVersion = {ids['schemaVersion']},",
        f"  registrySha256 = {lua_string(sha256(ids_path))},",
        "  entries = {", *entry_lines, "  },", "}", "",
    ])
    (generated / "content_ids.lua").write_text(ids_lua, encoding="utf-8")

    contract_lua = "\n".join([
        "-- GENERATED by scripts/generate-framework-data.py; do not edit.",
        "return {",
        f"  frameworkVersion = {int(features['rtt']['frameworkVersion'])},",
        f"  saveSchemaVersion = {save['currentVersion']},",
        f"  networkProtocolVersion = {network['protocolVersion']},",
        f"  engineBaseline = {lua_string(table_map['baseline'])},",
        f"  contentRegistrySha256 = {lua_string(sha256(ids_path))},",
        f"  saveSchemaSha256 = {lua_string(sha256(save_path))},",
        f"  networkPolicySha256 = {lua_string(sha256(network_path))},",
        "}", "",
    ])
    (generated / "contract.lua").write_text(contract_lua, encoding="utf-8")
    print(f"Generated RTT framework contract in {generated}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
